[project]
name = "hive-json-poster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kguelseven"}
]
requires-python = ">=3.13"
dependencies = [
    "beem>=0.24.26",
    "python-dotenv>=1.1.1",
]


